/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package base64work.vistasvj;

import java.awt.Dimension;
import java.net.InetAddress;
import java.util.logging.Level;
import java.util.logging.Logger;
import base64work.principalvj.MiVentana;
import base64work.subpanelesvj.Panel_BG;
import base64work.subpanelesvj.Panel_PY;
import base64work.principalvj.Sprites_Player;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import server.server_game;
/**
 *
 * @author Jorge
 */
public class Servidor extends javax.swing.JPanel {

    // Variables
    private server_game server = null;
    private Thread hiloG;
    private Panel_BG panelBG = null;
    private Panel_PY panelPY = null;
    private String BASE64_BG = null;
    private String BASE64_PY = null;
    ArrayList<String> strings = new ArrayList<String>();
    /**
     * Creates new form Servidor
     */
    public Servidor() {
        initComponents();
    }
    
    public Servidor(server_game server) {
        initComponents();
        // Resguardar referencia a servidor
        this.server = server;
        // Mi configuración
        // Escenario
        this.jPanelBG.setSize(200, 200);
        Dimension dim = this.jPanelBG.getSize();
        this.panelBG = new Panel_BG(dim.height, dim.width,
                new String[]{
                    "./__imagenes/Esc/Escenario1.jpg",
                    "./__imagenes/Esc/Escenario2.jpg"
                });
        this.BASE64_BG = this.panelBG.getActualImgAsString();
        this.panelBG.setVisible(true);
        this.jPanelBG.add(this.panelBG);
        this.jPanelBG.setVisible(true);
        // Jugador
        this.jPanelPY.setSize(200, 200);
        dim = this.jPanelPY.getSize();
        this.panelPY = new Panel_PY(dim.height, dim.width,
                new Sprites_Player[]{
                    new Sprites_Player("./__imagenes/Player_1", 150l /*Idle - Right*/, 100l /* Walk - Right*/),
                    new Sprites_Player("./__imagenes/Player_2", 150l /*Idle - Right*/, 100l /* Walk - Right*/)
                });
        this.BASE64_PY = this.panelPY.getActualImgAsString();
        this.panelPY.setVisible(true);
        this.jPanelPY.add(this.panelPY);
        this.jPanelPY.setVisible(true);
        // -------------------------------------
        // -------------------------------------
        // Crear e iniciar nuevo hilo
        this.hiloG = new Thread(){
            // Proceso secuncario
            public void run(){
                while (true) {
                    try {
                        Thread.sleep(10);
                        windowsPanelUpdate();
                    } catch (Exception e) {
                        Logger.getLogger(MiVentana.class.getName()).log(Level.SEVERE, null, e);
                    }
                }
            }
        };
        this.hiloG.start();
        // -------------------------------------
        // -------------------------------------
        // Seguro
        try {
            InetAddress IP = InetAddress.getLocalHost();
            String myIP = IP.getHostAddress();
            //txt_server_ip.setText(myIP);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    // Función de actualización
    public void windowsPanelUpdate() {
        // Actualizar canvas
        this.panelBG.repaint();
        this.panelPY.repaint();
    }
    
    public void stringDivider(String text){
        int index = 0;
        while (index < text.length()) {
            strings.add(text.substring(index, Math.min(index + 100,text.length())));
            index += 100;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelBG = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanelPY = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        start_game = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Selecciona configuración");

        jPanelBG.setPreferredSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout jPanelBGLayout = new javax.swing.GroupLayout(jPanelBG);
        jPanelBG.setLayout(jPanelBGLayout);
        jPanelBGLayout.setHorizontalGroup(
            jPanelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanelBGLayout.setVerticalGroup(
            jPanelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        jButton3.setText(">");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("<");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jPanelPY.setPreferredSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout jPanelPYLayout = new javax.swing.GroupLayout(jPanelPY);
        jPanelPY.setLayout(jPanelPYLayout);
        jPanelPYLayout.setHorizontalGroup(
            jPanelPYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanelPYLayout.setVerticalGroup(
            jPanelPYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        jButton5.setText(">");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("<");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        start_game.setText("Iniciar Juego");
        start_game.setToolTipText("");
        start_game.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start_gameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 40, Short.MAX_VALUE)
                                .addComponent(jPanelPY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)))
                        .addGap(27, 27, 27)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(start_game)
                .addGap(107, 107, 107))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jPanelBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addComponent(jPanelPY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(start_game)
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
   
    // ----------------------------------------------------------
    // ----------------------------------------------------------
    // ----------------------------------------------------------
    // Acciones para cambiar escenario
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.panelBG.prevImgToBG();
        this.BASE64_BG = this.panelBG.getActualImgAsString();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.panelBG.nextImgToBG();
        this.BASE64_BG = this.panelBG.getActualImgAsString();
        System.err.println("-------------------------------------");
        System.err.println("-------------------------------------");
        //System.err.println(this.BASE64_BG);
        System.err.println("-------------------------------------");
        System.err.println("-------------------------------------");
    }//GEN-LAST:event_jButton3ActionPerformed

    // ----------------------------------------------------------
    // ----------------------------------------------------------
    // ----------------------------------------------------------
    // Acciones para cambiar player
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.panelPY.prevImgsPlayer();
        this.BASE64_PY = this.panelPY.getActualImgAsString();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.panelPY.nextImgsPlayer();
        this.BASE64_PY = this.panelPY.getActualImgAsString();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void start_gameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start_gameActionPerformed
        // TODO add your handling code here:
        this.server.broadcast("SENDIMG");
        try {
            Thread.sleep(2000);
        } catch (InterruptedException ex) {
            Logger.getLogger(Servidor.class.getName()).log(Level.SEVERE, null, ex);
        }
        BufferedImage img = this.panelBG.getActualImg();    
        this.server.broadcastimg(img);
        System.out.println("Sending image");
        BufferedImage[][] imgsp = this.panelPY.getBufferedImagArray();
        try {
            Thread.sleep(2000);
        } catch (InterruptedException ex) {
            Logger.getLogger(Servidor.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (int x=0; x < imgsp.length; x++){
            for (int y=0; y < imgsp[x].length; y++){
                if(imgsp[x][y] != null){
                    this.server.broadcast("SENDIMG");
                    try {
                        Thread.sleep(2000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Servidor.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    this.server.broadcastimg(imgsp[x][y]);
                    System.out.println("Sending image");
                    try {
                        Thread.sleep(2000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Servidor.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }                  
        }
    }//GEN-LAST:event_start_gameActionPerformed

    // ----------------------------------------------------------
    // ----------------------------------------------------------
    // ----------------------------------------------------------
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelBG;
    private javax.swing.JPanel jPanelPY;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton start_game;
    // End of variables declaration//GEN-END:variables
}
